@url = http://localhost:3030/api/persons
###

GET {{url}}

###
GET http://localhost:3030/info

###
DELETE http://localhost:3030/api/persons/6018806a3a2956681615db73

###
POST http://localhost:3030/api/persons/
content-type: application/json

  {
    "name": "Aishat",
    "number": "767885322"
  }

###

PUT http://localhost:3030/api/persons/6017326e4484fa50ff015ffc
content-type: application/json

  {
    "name": "",
    "number": ""
  }