@url = http://localhost:3030/api/persons
###

GET {{url}}

###
GET http://localhost:3030/info

###
DELETE http://localhost:3030/api/persons/6015945bf3a2c53ce081a02c

###
POST http://localhost:3030/api/persons/
content-type: application/json

  {
    "name": "ELla Hellas",
    "number": "08077226154"
  }